### ISSUE TITLE
Get actions for next states by 'Qnet' or 'target_Qnet'?

### ISSUE THREAD

**Issue by zuzhaoye** [Shivanshu-Gupta/Pytorch-Double-DQN#1]
Hello, thank you so much for sharing this code structure! I got one thing no very sure about in your code.

https://github.com/Shivanshu-Gupta/Pytorch-Double-DQN/blob/1cff44d95d7881c6afc029b734508b1a705dfe14/agent.py#L94-L98

You obtain `next_state_actions` from `Qnet`, but the following webpage suggests that we should get `next_state_actions` from `target_Qnet`. May I know if there is any theory support for your choice or it's simply an error you made? Very much appreciated.

Website: https://towardsdatascience.com/double-deep-q-networks-905dd8325412

**Comment by Shivanshu-Gupta** [comment]
Looks to me that the mistake is in the blog you shared. Check out the [Double DQN paper](https://arxiv.org/pdf/1509.06461.pdf). Specifically, this is the target according to the paper: 

![image](https://user-images.githubusercontent.com/10811153/90672716-2ac72780-e274-11ea-983a-710e0e84816f.png)

i.e. the target network is used to get the Q-value for the next state when acting greedily according to the primary network. You may also refer to [this blog](https://medium.com/@qempsil0914/deep-q-learning-part2-double-deep-q-network-double-dqn-b8fc9212bbb2) instead.

**Comment by Shivanshu-Gupta** [comment]
Closing issue now. Feel free to let me know if you need more help.
